module.exports = {
	env: {
		TWITCH_CLIENT_ID: process.env.TWITCH_CLIENT_ID,
		TWITCH_CLIENT_SECRET: process.env.TWITCH_CLIENT_SECRET,
		GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID,
		GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET,
		GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
		NEXTAUTH_URL: process.env.NEXTAUTH_URL,
		DATABASE_URL: process.env.DATABASE_URL,
	},
};
